### ISSUE TITLE
Are there any plans to add a print option?

### ISSUE THREAD

**Issue by tylerlittlefield** [daranzolin/ViewPipeSteps#11]
I often prefer `print`ing the results instead of `View`ing them. Are there any plans to add a print option? Something like:

```r
library(dplyr)

my_chain <- "mtcars %>% 
  group_by(cyl) %>% 
  add_count()"

my_chain <- gsub("%>% \n", "%>% print() %>%", my_chain)

eval(parse(text = my_chain))
```

**Comment by daranzolin** [comment]
Possibly related to #10 
 
I wonder if this could also be a new operator to allow the user to control whether the pipe step `print`s or `View`s. Something like:

```
iris %>% 
   group_by(Species) %(P)% #print results
   summarize_if(is.numeric, mean) %(V)% #View results
   ungroup() %>% #nothing
   gather(measure, value, -Species) %(P)% #print results
   arrange(value) #View results?
```
I admit it looks very strange, but I like the idea of controlling result output.

**Comment by tylerlittlefield** [comment]
Nice, I like the idea. I think I would prefer something like:

```r
iris %>% 
  group_by(Species) %>%
  summarize_if(is.numeric, mean) %>%
  ungroup() %>% 
  gather(measure, value, -Species) %>%
  arrange(value) %>%
  steps(
    type = "print",    # print steps
    ignore = "ungroup" # ignore all ungroup calls
  )
```

Mainly because I would like to `print` the steps and once I'm happy with it, just remove the `steps` call from the end of the chain rather than replacing the new operators with the pipe. Though, one issue with this would be less user control, more broad, less specific. For example, you might not want to ignore all `group_by` calls, just a few specific ones.

**Comment by joachim-gassen** [comment]
As I mentioned in #10, personally I like to keep things simple. Once we have to start adding/modifying code to get ViewPipeSteps to work as we wish we can just modify the code for debugging purposes directly.
This being said, I think that a printing option would be nice to have. Could we just register a different addin?

**Comment by daranzolin** [comment]
While I am admittedly tempted to pack more functionality into this package, I agree that simplicity is best and registering a new printing addin makes the most sense.
