### ISSUE TITLE
"magrittr" as GitHub topic

### ISSUE THREAD

**Issue by katrinleinweber** [daranzolin/ViewPipeSteps#13]
Hello and thank you for building this! Helped me during several debugging sessions already :-)

How about [adding](https://blog.github.com/2017-01-31-introducing-topics/) this repo to [GitHub.com/topics/magrittr](https://github.com/topics/magrittr) in order to present it more prominently?

Cheers!

**Comment by daranzolin** [comment]
Done!

**Comment by katrinleinweber** [comment]
Cool, thanks :-)
