### ISSUE TITLE
The last step is not displayed

### ISSUE THREAD

**Issue by GegznaV** [daranzolin/ViewPipeSteps#16]
In this situation, the result of the last step `select(-indicator)` is not shown in a viewer tab:

```r
library(tidyverse)
library(data.table)

("
price   A      B      C     
1       TRUE   FALSE  FALSE 
2       FALSE  TRUE   FALSE 
3       TRUE   FALSE  FALSE 
4       FALSE  FALSE  TRUE  ") %>% 
  
  fread() %>% 
  
  pivot_longer(
    cols = c(A, B, C), 
    names_to = "condition", 
    values_to = "indicator"
  ) %>%
  
  filter(indicator) %>%
  
  select(-indicator)
```

I expect all the steps to be shown.

**Comment by joachim-gassen** [comment]
Sorry. Works for me. Are you using the current version?

**Comment by GegznaV** [comment]
The current GitHub version works well. I thought I updated it yesterday, but most probably something went wrong with the updates. Sorry for bothering you.

**Comment by joachim-gassen** [comment]
All good. Glad we sorted it out.
