### ISSUE TITLE
Feature request: Output under a chunk when working in Rmd

### ISSUE THREAD

**Issue by heinonmatti** [daranzolin/ViewPipeSteps#17]
I work in Rmarkdown and it'd be great to have output printed below the chunk like what happens when I run the chunk!

**Comment by joachim-gassen** [comment]
Thanks for the feature request. It motivated me to start implementing two extensions that allow printing all or selected pipe steps to the console by code. 

Would you mind testing the new code to see whether it does what you have in mind?

```
devtools::install_github("joachim-gassen/ViewPipeSteps")
library(tidyverse)
library(ViewPipeSteps)

diamonds %>%
  select(carat, cut, color, clarity, price) %>%
  group_by(color) %>%
  summarise(n = n(), price = mean(price)) %>%
  arrange(desc(color)) %>%
  print_pipe_steps() -> result
```

The above will print all pipe steps up to the `print_pipe_steps()` call. Alternatively, if you just want to print out selected pipe steps, you can also try the new experimental pipe variant.

```
diamonds %>%
  select(carat, cut, color, clarity, price) %>%
  group_by(color) %>%
  summarise(n = n(), price = mean(price)) %P>%
  arrange(desc(color)) -> result
```

Thanks for letting us know what you think. 

@daranzolin: Would you like including this into the main repo? I think that it will be helpful for people but am a little bit concerned that I start feature bloating this nice package.

**Comment by daranzolin** [comment]
@joachim-gassen I think it's a nifty addition! I say we merge into master.

**Comment by joachim-gassen** [comment]
OK. Thanks! I just issued the PR. Take your time. No need to hurry ;-)
