### ISSUE TITLE
Does this package work with package code?

### ISSUE THREAD

**Issue by lorenzwalthert** [daranzolin/ViewPipeSteps#2]
Hi @daranzolin, cool idea. I just tried it with [styler](https://github.com/r-lib/styler) source code in the after I set a break point somewhere in the code (function `default_style_guide_attributes()`) and it did not seem to work as I get the following error:
```r
Error: Pipe error at step 1. initialize_newlines: Error in eval(lhs, parent, parent): object 'pd_flat' not found
```
Executing the statement in the console worked.

**Comment by daranzolin** [comment]
Hmmm, I hadn't thought about this particular use case. And I confess I'm not entirely sure how addins function in other (non-interactive?) environments. Maybe putting that custom error message within a `if (interactive()) {...}` block would do the trick? Wish I knew more.

**Comment by lorenzwalthert** [comment]
Ok. I also don't know how they work unfortunately.
