### ISSUE TITLE
Addin fails if comments are present

### ISSUE THREAD

**Issue by GegznaV** [daranzolin/ViewPipeSteps#6]
`ViewPipeSteps` addin fails if comments are present. E.g.:

```r
library(tidyverse)

model <-
    # Create sequence
    data_frame(x = seq(-3, 3, by = .1)) %>% # Create sequence
    # Compute probability
    mutate(p = pnorm(x, mean = 0, sd = 1))
```

Consider removing lines that contain comments only and comments that follow after the pipe operator.

**Comment by daranzolin** [comment]
Thanks for filing this issue, I don't know how comments slipped my mind. 

My goal is to deploy a fix this weekend :crossed_fingers:

**Comment by daranzolin** [comment]
Should be fixed now!
